language: generic
include:
- os: linux
  addons:
    apt:
      update: true
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - debootstrap
      - genisoimage
      - p7zip-full
      - squashfs-tools
      - ubuntu-dev-tools
      - dpkg-dev
      - debhelper
      - fakeroot
      - devscripts
      - plymouth-label
      - plymouth-themes
sudo: required
dist: xenial
git:
  depth: 22
script:
- export LC_ALL=en_US.UTF-8
- export LANG=en_US.UTF-8
- export LANGUAGE=en_US.UTF-8
- chmod +x ./build.sh
- "./build.sh |& tee log.txt"
before_deploy:
- export image_name="`echo *.iso`"
- cat *.iso > "/home/travis/${image_name}"
- cat ../log.txt
- cp log.txt /home/travis/log.txt
notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lLgbB//VsHWekG2m4ab6bjdUwrJdfTmARikJCku2rcEg4NerlUm9qSajeZmwEHwhwOrc/2htP8lhNFT5adfwGqhUy0dY27K25hcLglq6oFA7/+7/UOlEgTuHrEPBxCeMcRJnY8IcsPppTPKtL6yYD1X4clFOneI1uXEwYYwGbhWNmlL/vqCk2p3sf0vl3bzQe3FEFRlnsGos7kMGxR9N2iQbZrYGYFNpHb4Q5BlaS2o3x1HTpG89u0X9fxK33inPve/AiTb3XnfMXuxshXBDxNbsOcovslHZH4Zp7Qy9dXULjoh25eVM24iBUPjKXEsksU6NGU2Hsj/bT31AzRxDy3mSs7FrJkuL4v1BGGJD+iODn6pbiKdybhB+i4ztBEjY/j3vk07bROC2venZRXrlKoUk8fvcd4ZcmK6pzCHLe3GNUe5LgPnMd1BIiP0WWe1SLftxkfI6gyW8VW6z9c/UynbgXiLwk/n+SN1EyJSEoPGWQ+WDZatcH8AvOhai5DayxAIbepzqkgVhLnzmz6oZvjTOLlznKkorMG181eojaPa6PJi6vEDxTWN2oYh03bTxkyM10wU3zzUraWCz4k1pQRtfvxvK/rNPCi35yCgPa3MHgaXxwHmM22OBmne7ohSsRwMm2fPd4lM0DTK+TUWxD38aJRuatMgsYQ99I253h2E=
  file_glob: true # http://stackoverflow.com/a/28579635/1320237
  file: 
    - "/home/travis/${image_name}"
    - "/home/travis/log.txt"
  on:
    all_branches: true
after_deploy:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/releases_maintainer.sh;
  fi
- cd scripts/mail-scripts && ./mail.py
after_failure:
- cd scripts/mail-scripts && ./mail-fail.py
